name: Build CMSimple_XH
on:
  workflow_dispatch:
    inputs:
      version:
        description: CMSimple_XH version to build
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phing
      - name: Checkout CMSimple_XH
        uses: actions/checkout@v3
      - name: Build CMSimple_XH
        run: phing build -Dversion=${{github.event.inputs.version}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CMSimple_XH-${{github.event.inputs.version}}
          path: CMSimple_XH-${{github.event.inputs.version}}.zip
